[project]
data_dir = "/data"
base_dir = "/workspace"
random_seed = 1234

[features]
frame_rate = 50
seq_len = 60000  # 1000 * 60 (60s in milliseconds)

[ml]
train_ratio = 0.83
validation_ratio = 0.1
test_ratio = 0.07

[voca]
tf_model = "models/ds_graph/output_graph.pb"
ds_model = "models/voca/gstep_52280.model"

[flame]
model_path_generic = "models/flame_model/ch_models/generic_model.pkl"
model_path_female = "models/flame_model/ch_models/female_model.pkl"
model_path_male = "models/flame_model/ch_models/male_model.pkl"
static_landmark_embedding_path = "models/flame_model/flame_static_embedding.pkl"
dynamic_landmark_embedding_path = "models/flame_model/flame_dynamic_embedding.npy"

[optuna]
rdbs_storage = ""

[comet]
api_key = ""
project_name = "lets_face_it"
